name: weather_app
description: "Simple weather app using using the open-meteo.com weather API"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.3.2
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  dio: ^5.5.0+1
  collection: ^1.18.0
  intl: ^0.19.0
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.2
  flutter_native_splash: ^2.4.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  freezed: ^2.5.7
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  json_serializable: ^6.8.0
  shared_preferences_tools: ^1.1.0

flutter:
  uses-material-design: true
  fonts:
  - family: NotoColorEmoji
    fonts:
      - asset: assets/fonts/NotoColorEmoji.ttf

# https://pub.dev/packages/flutter_native_splash/
flutter_native_splash:
  color: "#ffffff"